# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pose_messages.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'pose_messages.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13pose_messages.proto\x12\rpose_messages\"+\n\x04Pose\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\r\n\x05theta\x18\x03 \x01(\x01\"*\n\x07Vector3\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\"8\n\nQuaternion\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x12\t\n\x01w\x18\x04 \x01(\x01\x32\xc9\x01\n\x0bPoseService\x12\x34\n\x08SendPose\x12\x13.pose_messages.Pose\x1a\x13.pose_messages.Pose\x12<\n\nSendVector\x12\x16.pose_messages.Vector3\x1a\x16.pose_messages.Vector3\x12\x46\n\x0eSendQuaternion\x12\x19.pose_messages.Quaternion\x1a\x19.pose_messages.Quaternionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pose_messages_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POSE']._serialized_start=38
  _globals['_POSE']._serialized_end=81
  _globals['_VECTOR3']._serialized_start=83
  _globals['_VECTOR3']._serialized_end=125
  _globals['_QUATERNION']._serialized_start=127
  _globals['_QUATERNION']._serialized_end=183
  _globals['_POSESERVICE']._serialized_start=186
  _globals['_POSESERVICE']._serialized_end=387
# @@protoc_insertion_point(module_scope)
