# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: robot_service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'robot_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import std_msgs_pb2 as std__msgs__pb2
import nav_msgs_pb2 as nav__msgs__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13robot_service.proto\x12\rrobot_service\x1a\x0estd_msgs.proto\x1a\x0enav_msgs.proto\"<\n\x0e\x46loat32Request\x12*\n\nfloat_data\x18\x01 \x01(\x0b\x32\x16.robot_service.Float32\"0\n\x0bPoseRequest\x12!\n\x04pose\x18\x01 \x01(\x0b\x32\x13.robot_service.Pose\"=\n\x0f\x46loat32Response\x12*\n\nfloat_data\x18\x01 \x01(\x0b\x32\x16.robot_service.Float32\"1\n\x0cPoseResponse\x12!\n\x04pose\x18\x01 \x01(\x0b\x32\x13.robot_service.Pose2\xec\x01\n\x0cRobotService\x12K\n\nGetFloat32\x12\x1d.robot_service.Float32Request\x1a\x1e.robot_service.Float32Response\x12K\n\nSetFloat32\x12\x1d.robot_service.Float32Request\x1a\x1e.robot_service.Float32Response\x12\x42\n\x07SetPose\x12\x1a.robot_service.PoseRequest\x1a\x1b.robot_service.PoseResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FLOAT32REQUEST']._serialized_start=70
  _globals['_FLOAT32REQUEST']._serialized_end=130
  _globals['_POSEREQUEST']._serialized_start=132
  _globals['_POSEREQUEST']._serialized_end=180
  _globals['_FLOAT32RESPONSE']._serialized_start=182
  _globals['_FLOAT32RESPONSE']._serialized_end=243
  _globals['_POSERESPONSE']._serialized_start=245
  _globals['_POSERESPONSE']._serialized_end=294
  _globals['_ROBOTSERVICE']._serialized_start=297
  _globals['_ROBOTSERVICE']._serialized_end=533
# @@protoc_insertion_point(module_scope)
