# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import robot_service_pb2 as robot__service__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in robot_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RobotServiceStub(object):
    """========== Service Definitions ==========
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetFloat32 = channel.unary_unary(
                '/robot_service.RobotService/GetFloat32',
                request_serializer=robot__service__pb2.Float32Request.SerializeToString,
                response_deserializer=robot__service__pb2.Float32Response.FromString,
                _registered_method=True)
        self.SetFloat32 = channel.unary_unary(
                '/robot_service.RobotService/SetFloat32',
                request_serializer=robot__service__pb2.Float32Request.SerializeToString,
                response_deserializer=robot__service__pb2.Float32Response.FromString,
                _registered_method=True)
        self.SetPose = channel.unary_unary(
                '/robot_service.RobotService/SetPose',
                request_serializer=robot__service__pb2.PoseRequest.SerializeToString,
                response_deserializer=robot__service__pb2.PoseResponse.FromString,
                _registered_method=True)


class RobotServiceServicer(object):
    """========== Service Definitions ==========
    """

    def GetFloat32(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetFloat32(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPose(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RobotServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetFloat32': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFloat32,
                    request_deserializer=robot__service__pb2.Float32Request.FromString,
                    response_serializer=robot__service__pb2.Float32Response.SerializeToString,
            ),
            'SetFloat32': grpc.unary_unary_rpc_method_handler(
                    servicer.SetFloat32,
                    request_deserializer=robot__service__pb2.Float32Request.FromString,
                    response_serializer=robot__service__pb2.Float32Response.SerializeToString,
            ),
            'SetPose': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPose,
                    request_deserializer=robot__service__pb2.PoseRequest.FromString,
                    response_serializer=robot__service__pb2.PoseResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'robot_service.RobotService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('robot_service.RobotService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RobotService(object):
    """========== Service Definitions ==========
    """

    @staticmethod
    def GetFloat32(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot_service.RobotService/GetFloat32',
            robot__service__pb2.Float32Request.SerializeToString,
            robot__service__pb2.Float32Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetFloat32(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot_service.RobotService/SetFloat32',
            robot__service__pb2.Float32Request.SerializeToString,
            robot__service__pb2.Float32Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetPose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot_service.RobotService/SetPose',
            robot__service__pb2.PoseRequest.SerializeToString,
            robot__service__pb2.PoseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
