// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: robot_service.proto

#include "robot_service.pb.h"
#include "robot_service.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace robot_service {

static const char* RobotService_method_names[] = {
  "/robot_service.RobotService/GetFloat32",
  "/robot_service.RobotService/SetFloat32",
  "/robot_service.RobotService/SetPose",
};

std::unique_ptr< RobotService::Stub> RobotService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< RobotService::Stub> stub(new RobotService::Stub(channel, options));
  return stub;
}

RobotService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetFloat32_(RobotService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetFloat32_(RobotService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetPose_(RobotService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status RobotService::Stub::GetFloat32(::grpc::ClientContext* context, const ::robot_service::Float32Request& request, ::robot_service::Float32Response* response) {
  return ::grpc::internal::BlockingUnaryCall< ::robot_service::Float32Request, ::robot_service::Float32Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetFloat32_, context, request, response);
}

void RobotService::Stub::async::GetFloat32(::grpc::ClientContext* context, const ::robot_service::Float32Request* request, ::robot_service::Float32Response* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::robot_service::Float32Request, ::robot_service::Float32Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetFloat32_, context, request, response, std::move(f));
}

void RobotService::Stub::async::GetFloat32(::grpc::ClientContext* context, const ::robot_service::Float32Request* request, ::robot_service::Float32Response* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetFloat32_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::robot_service::Float32Response>* RobotService::Stub::PrepareAsyncGetFloat32Raw(::grpc::ClientContext* context, const ::robot_service::Float32Request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::robot_service::Float32Response, ::robot_service::Float32Request, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetFloat32_, context, request);
}

::grpc::ClientAsyncResponseReader< ::robot_service::Float32Response>* RobotService::Stub::AsyncGetFloat32Raw(::grpc::ClientContext* context, const ::robot_service::Float32Request& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetFloat32Raw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status RobotService::Stub::SetFloat32(::grpc::ClientContext* context, const ::robot_service::Float32Request& request, ::robot_service::Float32Response* response) {
  return ::grpc::internal::BlockingUnaryCall< ::robot_service::Float32Request, ::robot_service::Float32Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetFloat32_, context, request, response);
}

void RobotService::Stub::async::SetFloat32(::grpc::ClientContext* context, const ::robot_service::Float32Request* request, ::robot_service::Float32Response* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::robot_service::Float32Request, ::robot_service::Float32Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetFloat32_, context, request, response, std::move(f));
}

void RobotService::Stub::async::SetFloat32(::grpc::ClientContext* context, const ::robot_service::Float32Request* request, ::robot_service::Float32Response* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetFloat32_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::robot_service::Float32Response>* RobotService::Stub::PrepareAsyncSetFloat32Raw(::grpc::ClientContext* context, const ::robot_service::Float32Request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::robot_service::Float32Response, ::robot_service::Float32Request, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetFloat32_, context, request);
}

::grpc::ClientAsyncResponseReader< ::robot_service::Float32Response>* RobotService::Stub::AsyncSetFloat32Raw(::grpc::ClientContext* context, const ::robot_service::Float32Request& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetFloat32Raw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status RobotService::Stub::SetPose(::grpc::ClientContext* context, const ::robot_service::PoseRequest& request, ::robot_service::PoseResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::robot_service::PoseRequest, ::robot_service::PoseResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetPose_, context, request, response);
}

void RobotService::Stub::async::SetPose(::grpc::ClientContext* context, const ::robot_service::PoseRequest* request, ::robot_service::PoseResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::robot_service::PoseRequest, ::robot_service::PoseResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetPose_, context, request, response, std::move(f));
}

void RobotService::Stub::async::SetPose(::grpc::ClientContext* context, const ::robot_service::PoseRequest* request, ::robot_service::PoseResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetPose_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::robot_service::PoseResponse>* RobotService::Stub::PrepareAsyncSetPoseRaw(::grpc::ClientContext* context, const ::robot_service::PoseRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::robot_service::PoseResponse, ::robot_service::PoseRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetPose_, context, request);
}

::grpc::ClientAsyncResponseReader< ::robot_service::PoseResponse>* RobotService::Stub::AsyncSetPoseRaw(::grpc::ClientContext* context, const ::robot_service::PoseRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetPoseRaw(context, request, cq);
  result->StartCall();
  return result;
}

RobotService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RobotService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RobotService::Service, ::robot_service::Float32Request, ::robot_service::Float32Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RobotService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::robot_service::Float32Request* req,
             ::robot_service::Float32Response* resp) {
               return service->GetFloat32(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RobotService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RobotService::Service, ::robot_service::Float32Request, ::robot_service::Float32Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RobotService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::robot_service::Float32Request* req,
             ::robot_service::Float32Response* resp) {
               return service->SetFloat32(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RobotService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RobotService::Service, ::robot_service::PoseRequest, ::robot_service::PoseResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RobotService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::robot_service::PoseRequest* req,
             ::robot_service::PoseResponse* resp) {
               return service->SetPose(ctx, req, resp);
             }, this)));
}

RobotService::Service::~Service() {
}

::grpc::Status RobotService::Service::GetFloat32(::grpc::ServerContext* context, const ::robot_service::Float32Request* request, ::robot_service::Float32Response* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RobotService::Service::SetFloat32(::grpc::ServerContext* context, const ::robot_service::Float32Request* request, ::robot_service::Float32Response* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status RobotService::Service::SetPose(::grpc::ServerContext* context, const ::robot_service::PoseRequest* request, ::robot_service::PoseResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace robot_service

